sudo: false
language: ruby

install: 'gem install bundler; bundle install --retry=3'
script: 'ruby -vr bundler/setup -S rake test'

matrix:
  include:
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: ruby-head
    - rvm: jruby
      env: JRUBY_OPTS=--debug

  allow_failures:
    - rvm: 2.4
