sudo: false
language: ruby
rvm:
  - 2.2
  - 2.3.1
  - rbx
  - jruby-9

before_install:
  - rvm get head
  - rvm reload
  - rvm use --install $TRAVIS_RUBY_VERSION --binary --latest
install: 'gem install bundler; bundle install --retry=3'
script: 'ruby -vr bundler/setup -S rake test'
